' Gambas module file

Private rutaficherofuentes As String = User.home & "/.ControlFlujoCaja/casas.datos"

Public Sub guardardatos(origen As String, destino As String, valor As Float, obs As String)

    Dim contenido As String
    Dim lineaDatos As String

    lineaDatos = origen & "|"
    lineaDatos &= destino & "|"
    lineaDatos &= Str$(valor) & "|"
    lineaDatos &= obs & "|"
    lineaDatos &= Format(Now, "yyyy/mm/dd hh:nn:ss") & "\n"

    ComprobarExistenciaFicheroDatos()
    'leo datos anteriores
    contenido = File.Load(rutaficherofuentes)
    'añado datos nuevos
    contenido &= lineaDatos
    'guardos datos
    File.Save(rutaficheroFuentes, contenido)
    'emitir un evento para actualizar datos

End

Private Sub ComprobarExistenciaFicheroDatos()

    If Not Exist(rutaficheroFuentes) Then
        'hay que crearlo..
        Try Mkdir User.home & "/.ControlFlujoCaja" 'creo ruta
        File.Save(rutaficheroFuentes, "") 'creo archivo vacio
    Endif

End

Public Sub Recalculo(GridViewFuentes As Gridview)

    Dim contador As Integer
    Dim arrayFuentes As CasaApuesta[]
    'leo el fichero de datos
    ComprobarExistenciaFicheroDatos()

    GestorCasaDeApuestas.HacerCalculos(rutaficherofuentes)

    'actualizao gridview los datos

    ArrayFuentes = GestorCasaDeApuestas.Estado()

    GridViewFuentes.Rows.count = arrayFuentes.count
    contador = -1
    While contador < ArrayFuentes.max - 1
        contador += 1
        With GridViewFuentes

            .[contador, 0].text = arrayFuentes[contador].nombre
            .[contador, 1].text = Format(arrayFuentes[contador].Saldo, "$,0.#0")

            If arrayFuentes[contador].Saldo < 0 Then
                .[contador, 1].foreground = Color.red
            Else
                .[contador, 1].foreground = Color.Black
            Endif

        End With
    Wend

End
